title: Resume Example Projects and (Some) Work projects
description: Some projects made by Rik Timmers
#theme: jekyll-theme-midnight
theme: just-the-docs

# Enable search
search_enabled: true

# Navigation behavior
nav_sort: case_sensitive

# URL behavior
permalink: pretty
